gem:
  # Add your `gem` command parameters here:
  #
  exclude:
   - reline
   - net-imap
   - net-protocol
   - net-smtp
  typed_overrides:
    timeout: "false"
    msgpack: "false"
  # doc: true
  # workers: 5
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
